export const jobData = [
  {
    "id": 1,
    "company": "Photosnap",
    "featured": true,
    "position": "Senior Frontend Developer",
    "role": "Frontend",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": ["React"]
  },
  {
    "id": 2,
    "company": "Manage",
    "featured": true,
    "position": "Fullstack Developer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1d ago",
    "contract": "Part Time",
    "location": "Mumbai",
    "languages": ["Python"],
    "tools": ["React"]
  },
  {
    "id": 3,
    "company": "Account",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 4,
    "company": "MyHome",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "5d ago",
    "contract": "Contract",
    "location": "Kolkata",
    "languages": ["CSS", "JavaScript"],
    "tools": ["React"]
  },
  {
    "id": 5,
    "company": "Loop Studios",
    "featured": false,
    "position": "Software Engineer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Ruby", "Sass"]
  },
  {
    "id": 6,
    "company": "FaceIt",
    "featured": false,
    "position": "Junior Backend Developer",
    "role": "Backend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Ruby"],
    "tools": ["RoR"]
  },
  {
    "id": 7,
    "company": "Shortly",
    "featured": false,
    "position": "Junior Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["HTML", "JavaScript"],
    "tools": ["Sass"]
  },
  {
    "id": 8,
    "company": "Insure",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["JavaScript"],
    "tools": ["Vue", "Sass"]
  },
  {
    "id": 9,
    "company": "Eyecam Co.",
    "featured": false,
    "position": "Full Stack Engineer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript", "Python"],
    "tools": ["Django"]
  },
  {
    "id": 10,
    "company": "The Air Filter Company",
    "featured": false,
    "position": "Front-end Dev",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Part Time",
    "location": "Delhi",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 11,
    "company": "CodeX",
    "featured": true,
    "position": "Senior Software Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "3d ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["Java", "JavaScript"],
    "tools": ["Spring", "React"]
  },
  {
    "id": 12,
    "company": "ByteWorks",
    "featured": false,
    "position": "Data Analyst",
    "role": "Data",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Contract",
    "location": "Kolkata",
    "languages": ["Python", "SQL"],
    "tools": ["Pandas", "Tableau"]
  },
  {
    "id": 13,
    "company": "WebCrafters",
    "featured": true,
    "position": "UX Designer",
    "role": "Design",
    "level": "Senior",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["C++"],
    "tools": ["Figma", "Sketch"]
  },
  {
    "id": 14,
    "company": "DataStream",
    "featured": false,
    "position": "Backend Developer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "2w ago",
    "contract": "Part Time",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["Django", "PostgreSQL"]
  },
  {
    "id": 15,
    "company": "MobileMinds",
    "featured": false,
    "position": "Mobile Engineer",
    "role": "Fullstack",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["Kotlin", "Swift"],
    "tools": ["Android Studio", "Xcode"]
  },
  {
    "id": 16,
    "company": "CloudTech",
    "featured": true,
    "position": "DevOps Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "2d ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["Bash", "Python"],
    "tools": ["Docker", "Kubernetes"]
  },
  {
    "id": 17,
    "company": "QA Solutions",
    "featured": false,
    "position": "QA Tester",
    "role": "QA",
    "level": "Midweight",
    "postedAt": "5d ago",
    "contract": "Part Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Selenium", "Cypress"]
  },
  {
    "id": 18,
    "company": "ProductPro",
    "featured": false,
    "position": "Product Manager",
    "role": "Management",
    "level": "Senior",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Java"],
    "tools": ["Jira", "Confluence"]
  },
  {
    "id": 19,
    "company": "SecureNet",
    "featured": true,
    "position": "Security Analyst",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "3w ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["Python"],
    "tools": ["Nmap", "Burp Suite"]
  },
  {
    "id": 20,
    "company": "TechWriters",
    "featured": false,
    "position": "Technical Writer",
    "role": "QA",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Part Time",
    "location": "Kolkata",
    "languages": ["Python", "Ruby"],
    "tools": ["Docsify", "Sphinx"]
  },
  {
    "id": 21,
    "company": "CloudLeap",
    "featured": false,
    "position": "Cloud Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["Python", "AWS"],
    "tools": ["EC2", "Lambda"]
  },
  {
    "id": 22,
    "company": "AITech",
    "featured": true,
    "position": "AI Researcher",
    "role": "Data",
    "level": "Midweight",
    "postedAt": "2d ago",
    "contract": "Contract",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["TensorFlow", "PyTorch"]
  },
  {
    "id": 23,
    "company": "SystemSolve",
    "featured": false,
    "position": "Systems Engineer",
    "role": "Fullstack",
    "level": "Junior",
    "postedAt": "3d ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["C#"],
    "tools": ["Linux", "Bash"]
  },
  {
    "id": 24,
    "company": "NetWorks",
    "featured": false,
    "position": "Network Administrator",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["C#"],
    "tools": ["Cisco", "CCNA"]
  },
  {
    "id": 25,
    "company": "TechLeaders",
    "featured": true,
    "position": "Tech Lead",
    "role": "Management",
    "level": "Senior",
    "postedAt": "5d ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["Java"],
    "tools": ["Maven", "Git"]
  },
  {
    "id": 26,
    "company": "ITConsult",
    "featured": false,
    "position": "IT Consultant",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Contract",
    "location": "Delhi",
    "languages": ["C"],
    "tools": ["AWS", "Azure"]
  },
  {
    "id": 27,
    "company": "BizAnalytica",
    "featured": false,
    "position": "Business Analyst",
    "role": "Management",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["C++"],
    "tools": ["Excel", "SQL"]
  },
  {
    "id": 28,
    "company": "SupportGenie",
    "featured": true,
    "position": "Tech Support",
    "role": "QA",
    "level": "Junior",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["Carbon"],
    "tools": ["ServiceNow", "Zendesk"]
  },
  {
    "id": 29,
    "company": "DataCrafters",
    "featured": false,
    "position": "Data Engineer",
    "role": "Data",
    "level": "Midweight",
    "postedAt": "1mo ago",
    "contract": "Contract",
    "location": "Mumbai",
    "languages": ["Python", "SQL"],
    "tools": ["Spark", "Hadoop"]
  },
  {
    "id": 30,
    "company": "ProjectFlow",
    "featured": false,
    "position": "Project Manager",
    "role": "Management",
    "level": "Senior",
    "postedAt": "2mo ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Golang"],
    "tools": ["Jira", "MS Project"]
  },
  {
    "id": 31,
    "company": "CyberGuard",
    "featured": true,
    "position": "Cybersecurity Engineer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["Python"],
    "tools": ["Wireshark", "Nessus"]
  },
  {
    "id": 32,
    "company": "GameDevs",
    "featured": false,
    "position": "Game Developer",
    "role": "Fullstack",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "Kolkata",
    "languages": ["C#"],
    "tools": ["Unity", "Unreal Engine"]
  },
  {
    "id": 33,
    "company": "EmbeddedTech",
    "featured": true,
    "position": "Embedded Engineer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["C", "C++"],
    "tools": ["Arduino", "Raspberry Pi"]
  },
  {
    "id": 34,
    "company": "AIMinds",
    "featured": false,
    "position": "Machine Learning Engineer",
    "role": "Data",
    "level": "Senior",
    "postedAt": "5d ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["TensorFlow", "Keras"]
  },
  {
    "id": 35,
    "company": "WebAppDev",
    "featured": true,
    "position": "Web Developer",
    "role": "Frontend",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": ["React", "Angular"]
  },
  {
    "id": 36,
    "company": "TestPro",
    "featured": false,
    "position": "Software Tester",
    "role": "QA",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Part Time",
    "location": "Kolkata",
    "languages": ["Python"],
    "tools": ["Selenium", "JUnit"]
  },
  {
    "id": 37,
    "company": "ITManagers",
    "featured": false,
    "position": "IT Manager",
    "role": "Management",
    "level": "Senior",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["C"],
    "tools": ["ITIL", "PMP"]
  },
  {
    "id": 38,
    "company": "QuantumVista",
    "featured": true,
    "position": "Senior Frontend Developer",
    "role": "Frontend",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": ["Android Studio"]
  },
  {
    "id": 39,
    "company": "ApexDigital",
    "featured": true,
    "position": "Fullstack Developer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1d ago",
    "contract": "Part Time",
    "location": "Mumbai",
    "languages": ["Python"],
    "tools": ["React"]
  },
  {
    "id": 40,
    "company": "NovaSolutions",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 41,
    "company": "ZenithTech",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "5d ago",
    "contract": "Contract",
    "location": "Kolkata",
    "languages": ["CSS", "JavaScript"],
    "tools": ["Ruby", "Sass"]
  },
  {
    "id": 42,
    "company": "ByteForge",
    "featured": false,
    "position": "Software Engineer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Ruby", "Sass"]
  },
  {
    "id": 43,
    "company": "CodeCraftersInc",
    "featured": false,
    "position": "Junior Backend Developer",
    "role": "Backend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Ruby"],
    "tools": ["RoR"]
  },
  {
    "id": 44,
    "company": "PixelPulse",
    "featured": false,
    "position": "Junior Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["HTML", "JavaScript"],
    "tools": ["Sass"]
  },
  {
    "id": 45,
    "company": "LogicLabs",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["JavaScript"],
    "tools": ["Vue", "Sass"]
  },
  {
    "id": 46,
    "company": "DataNexus",
    "featured": false,
    "position": "Full Stack Engineer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript", "Python"],
    "tools": ["Django"]
  },
  {
    "id": 47,
    "company": "CloudGrid",
    "featured": false,
    "position": "Front-end Dev",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Part Time",
    "location": "Delhi",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 48,
    "company": "VisionaryCode",
    "featured": true,
    "position": "Senior Software Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "3d ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["Java", "JavaScript"],
    "tools": ["Spring", "React"]
  },
  {
    "id": 49,
    "company": "StreamlineData",
    "featured": false,
    "position": "Data Analyst",
    "role": "Data",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Contract",
    "location": "Kolkata",
    "languages": ["Python", "SQL"],
    "tools": ["Pandas", "Tableau"]
  },
  {
    "id": 50,
    "company": "DesignSphere",
    "featured": true,
    "position": "UX Designer",
    "role": "Design",
    "level": "Senior",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["SQL"],
    "tools": ["Figma", "Sketch"]
  },
  {
    "id": 51,
    "company": "BackendBuilders",
    "featured": false,
    "position": "Backend Developer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "2w ago",
    "contract": "Part Time",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["Django", "PostgreSQL"]
  },
  {
    "id": 52,
    "company": "MobileMasters",
    "featured": false,
    "position": "Mobile Engineer",
    "role": "Fullstack",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["Kotlin", "Swift"],
    "tools": ["Android Studio", "Xcode"]
  },
  {
    "id": 53,
    "company": "CloudConstruct",
    "featured": true,
    "position": "DevOps Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "2d ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["Bash", "Python"],
    "tools": ["Docker", "Kubernetes"]
  },
  {
    "id": 54,
    "company": "QualityAssure",
    "featured": false,
    "position": "QA Tester",
    "role": "QA",
    "level": "Midweight",
    "postedAt": "5d ago",
    "contract": "Part Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Selenium", "Cypress"]
  },
  {
    "id": 55,
    "company": "ProductPulseInc",
    "featured": false,
    "position": "Product Manager",
    "role": "Management",
    "level": "Senior",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Java"],
    "tools": ["Jira", "Confluence"]
  },
  {
    "id": 56,
    "company": "SecureSphere",
    "featured": true,
    "position": "Security Analyst",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "3w ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["Python"],
    "tools": ["Nmap", "Burp Suite"]
  },
  {
    "id": 57,
    "company": "SecureSpaces",
    "featured": true,
    "position": "Security Analyst",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "4w ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["Python"],
    "tools": ["Nmap", "Burp Suite"]
  },
  {
    "id": 58,
    "company": "PixelPioneers",
    "featured": true,
    "position": "Senior Frontend Developer",
    "role": "Frontend",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": ["React"]
  },
  {
    "id": 59,
    "company": "CodeMasters",
    "featured": true,
    "position": "Fullstack Developer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1d ago",
    "contract": "Part Time",
    "location": "Mumbai",
    "languages": ["Python"],
    "tools": ["React"]
  },
  {
    "id": 60,
    "company": "TechNest",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 61,
    "company": "WebWizards",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "5d ago",
    "contract": "Contract",
    "location": "Kolkata",
    "languages": ["CSS", "JavaScript"],
    "tools": ["React"]
  },
  {
    "id": 62,
    "company": "DevCraft",
    "featured": false,
    "position": "Software Engineer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Ruby", "Sass"]
  },
  {
    "id": 63,
    "company": "CodeForge",
    "featured": false,
    "position": "Junior Backend Developer",
    "role": "Backend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Ruby"],
    "tools": ["RoR"]
  },
  {
    "id": 64,
    "company": "TechHive",
    "featured": false,
    "position": "Junior Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["HTML", "JavaScript"],
    "tools": ["Sass"]
  },
  {
    "id": 65,
    "company": "CodeSphere",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["JavaScript"],
    "tools": ["Vue", "Sass"]
  },
  {
    "id": 66,
    "company": "DevNest",
    "featured": false,
    "position": "Full Stack Engineer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript", "Python"],
    "tools": ["Django"]
  },
  {
    "id": 67,
    "company": "TechPulse",
    "featured": false,
    "position": "Front-end Dev",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Part Time",
    "location": "Delhi",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 68,
    "company": "CodeCrafters",
    "featured": true,
    "position": "Senior Software Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "3d ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["Java", "JavaScript"],
    "tools": ["Spring", "React"]
  },
  {
    "id": 69,
    "company": "DataDriven",
    "featured": false,
    "position": "Data Analyst",
    "role": "Data",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Contract",
    "location": "Kolkata",
    "languages": ["Python", "SQL"],
    "tools": ["Pandas", "Tableau"]
  },
  {
    "id": 70,
    "company": "DesignHive",
    "featured": true,
    "position": "UX Designer",
    "role": "Design",
    "level": "Senior",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["Java"],
    "tools": ["Figma", "Sketch"]
  },
  {
    "id": 71,
    "company": "BackendMasters",
    "featured": false,
    "position": "Backend Developer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "2w ago",
    "contract": "Part Time",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["Django", "PostgreSQL"]
  },
  {
    "id": 72,
    "company": "MobileCraft",
    "featured": false,
    "position": "Mobile Engineer",
    "role": "Fullstack",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["Kotlin", "Swift"],
    "tools": ["Android Studio", "Xcode"]
  },
  {
    "id": 73,
    "company": "CloudPulse",
    "featured": true,
    "position": "DevOps Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "2d ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["Bash", "Python"],
    "tools": ["Docker", "Kubernetes"]
  },
  {
    "id": 74,
    "company": "QATech",
    "featured": false,
    "position": "QA Tester",
    "role": "QA",
    "level": "Midweight",
    "postedAt": "5d ago",
    "contract": "Part Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Selenium", "Cypress"]
  },
  {
    "id": 75,
    "company": "ProductHive",
    "featured": false,
    "position": "Product Manager",
    "role": "Management",
    "level": "Senior",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Java"],
    "tools": ["Jira", "Confluence"]
  },
  {
    "id": 76,
    "company": "SecureHive",
    "featured": true,
    "position": "Security Analyst",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "3w ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["Python"],
    "tools": ["Nmap", "Burp Suite"]
  },
  {
    "id": 77,
    "company": "TechWritersPro",
    "featured": false,
    "position": "Technical Writer",
    "role": "QA",
    "level": "Junior",
    "postedAt": "1mo ago",
    "contract": "Part Time",
    "location": "Kolkata",
    "languages": ["Java"],
    "tools": ["Docsify", "Sphinx"]
  },
  {
    "id": 78,
    "company": "CloudCrafters",
    "featured": false,
    "position": "Cloud Engineer",
    "role": "Fullstack",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["Python", "AWS"],
    "tools": ["EC2", "Lambda"]
  },
  {
    "id": 79,
    "company": "AIForge",
    "featured": true,
    "position": "AI Researcher",
    "role": "Data",
    "level": "Midweight",
    "postedAt": "2d ago",
    "contract": "Contract",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["TensorFlow", "PyTorch"]
  },
  {
    "id": 80,
    "company": "SysTech",
    "featured": false,
    "position": "Systems Engineer",
    "role": "Fullstack",
    "level": "Junior",
    "postedAt": "3d ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["C++"],
    "tools": ["Linux", "Bash"]
  },
  {
    "id": 81,
    "company": "NetCrafters",
    "featured": false,
    "position": "Network Administrator",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["C++"],
    "tools": ["Cisco", "CCNA"]
  },
  {
    "id": 82,
    "company": "TechLeadersPro",
    "featured": true,
    "position": "Tech Lead",
    "role": "Management",
    "level": "Senior",
    "postedAt": "5d ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["Java"],
    "tools": ["Maven", "Git"]
  },
  {
    "id": 83,
    "company": "ITConsultPro",
    "featured": false,
    "position": "IT Consultant",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Contract",
    "location": "Delhi",
    "languages": ["C++"],
    "tools": ["AWS", "Azure"]
  },
  {
    "id": 84,
    "company": "BizTech",
    "featured": false,
    "position": "Business Analyst",
    "role": "Management",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["C"],
    "tools": ["Excel", "SQL"]
  },
  {
    "id": 85,
    "company": "SupportTech",
    "featured": true,
    "position": "Tech Support",
    "role": "QA",
    "level": "Junior",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Kolkata",
    "languages": ["C"],
    "tools": ["ServiceNow", "Zendesk"]
  },
  {
    "id": 86,
    "company": "DataForge",
    "featured": false,
    "position": "Data Engineer",
    "role": "Data",
    "level": "Midweight",
    "postedAt": "1mo ago",
    "contract": "Contract",
    "location": "Mumbai",
    "languages": ["Python", "SQL"],
    "tools": ["Spark", "Hadoop"]
  },
  {
    "id": 87,
    "company": "ProjectCrafters",
    "featured": false,
    "position": "Project Manager",
    "role": "Management",
    "level": "Senior",
    "postedAt": "2mo ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["Jira", "MS Project"]
  },
  {
    "id": 88,
    "company": "CyberForge",
    "featured": true,
    "position": "Cybersecurity Engineer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["Python"],
    "tools": ["Wireshark", "Nessus"]
  },
  {
    "id": 89,
    "company": "GameCrafters",
    "featured": false,
    "position": "Game Developer",
    "role": "Fullstack",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "Kolkata",
    "languages": ["C#"],
    "tools": ["Unity", "Unreal Engine"]
  },
  {
    "id": 90,
    "company": "EmbeddedForge",
    "featured": true,
    "position": "Embedded Engineer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["C", "C++"],
    "tools": ["Arduino", "Raspberry Pi"]
  },
  {
    "id": 91,
    "company": "AICrafters",
    "featured": false,
    "position": "Machine Learning Engineer",
    "role": "Data",
    "level": "Senior",
    "postedAt": "5d ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["Python"],
    "tools": ["TensorFlow", "Keras"]
  },
  {
    "id": 92,
    "company": "WebForge",
    "featured": true,
    "position": "Web Developer",
    "role": "Frontend",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Contract",
    "location": "Chennai",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": ["React", "Angular"]
  },
  {
    "id": 93,
    "company": "TestCrafters",
    "featured": false,
    "position": "Software Tester",














    
    "role": "QA",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Part Time",
    "location": "Kolkata",
    "languages": ["Python"],
    "tools": ["Selenium", "JUnit"]
  },
  {
    "id": 94,
    "company": "ITLeaders",
    "featured": false,
    "position": "IT Manager",
    "role": "Management",
    "level": "Senior",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["Python"],
    "tools": ["ITIL", "PMP"]
  },
  {
    "id": 95,
    "company": "QuantumForge",
    "featured": true,
    "position": "Senior Frontend Developer",
    "role": "Frontend",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": ["Python"]
  },
  {
    "id": 96,
    "company": "ApexCrafters",
    "featured": true,
    "position": "Fullstack Developer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1d ago",
    "contract": "Part Time",
    "location": "Mumbai",
    "languages": ["Python"],
    "tools": ["React"]
  },
  {
    "id": 97,
    "company": "NovaForge",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "Chennai",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 98,
    "company": "ZenithForge",
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "5d ago",
    "contract": "Contract",
    "location": "Kolkata",
    "languages": ["CSS", "JavaScript"],
    "tools": ["React"]
  },
  {
    "id": 99,
    "company": "ByteCrafters",
    "featured": false,
    "position": "Software Engineer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Ruby", "Sass"]
  },
  {
    "id": 100,
    "company": "TechTitans",
    "featured": true,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Delhi",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": ["Ruby", "Sass"]
  }
];
